spring.application.name=password-generator
password.generator.numberOfSmallLetter=2
password.generator.numberOfCapitalLetter=2
password.generator.numberOfDigits=2
password.generator.numberOfSpecialChars=2
